### ISSUE TITLE
Implement checkAlignment protocol

### ISSUE THREAD

**Issue by jasonrute** [IBM/graph2tac#38]
From @LasseBlaauwbroek:

Starting with v10, there is a new command Check Neural Alignment in Coq, that reports how many tactics and definitions cannot be algined to the trained dataset. For this, a simple protocol needs to be implemented in g2t-server:

https://github.com/coq-tactician/coq-tactician-reinforce/blob/68ca1b479daae971079cda666fa47aa82906a7e6/graph_api.capnp#L440-L446

https://github.com/coq-tactician/coq-tactician-reinforce/blob/68ca1b479daae971079cda666fa47aa82906a7e6/graph_api.capnp#L467-L470

**Comment by jasonrute** [comment]
Vasily says this has been done.

**Comment by LasseBlaauwbroek** [comment]
Done
