### ISSUE TITLE
Transition to v12

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [IBM/graph2tac#83]
Tasks to make graph2tac compatible with v12 in order of importance.

- [x] Make the loader compile with v12. This likely only involves small changes in the following structures:
  `ProofState.root`, `ProofState.context`, `Outcome.term`.

At this point, v12 should be trainable and benchmarkable. With these changes, we should run a comparison
between v11 and v12-unshared, to check the effects of the currying of the `app` nodes. So please make sure
that a branch with only this change and none of the changes below is available.

- [x] Modify the server to align definitions based on `Graph.Node.identity` instead of `Definition.name`.
  Note that `Graph.Node.identity` is not unique within the dataset, but it should be valid to choose an
  arbitrary node with the correct identity.
- [ ] ~~Remove the hash-calculation from the hmodel and use `Graph.Node.identity` instead.~~
- [x] Remove the definition-cluster calculation code, and use the information stored in `Definition.inductive`,
  `Definition.constructor` and `Definition.projection` instead.
- [x] Come up with a protocol for incremental sending of unseen definitions to the server based on the hashes
  of the definitions.

**Comment by jasonrute** [comment]
Thanks @LasseBlaauwbroek!  Just some quick thoughts off hand:
* For `ProofState.root`, `ProofState.context`, `Outcome.term` I assume you are referring to datastructures in the capn proto file and not in Graph2Tac right?
* ProofState.root might be a bit tricky.  A bunch of our code hard codes it to `0` ignoring whatever is set. But at the same time, I have no idea if LoaderProofState.root in graph2tac has anything to do with the ProofState.root you are talking about.

**Comment by LasseBlaauwbroek** [comment]
- Yes
- As far as I can tell, these things are unrelated. `LoaderProofState.root` is one layer of abstraction higher than `ProofState.root`.

**Comment by LasseBlaauwbroek** [comment]
This is basically done.
